### ISSUE TITLE
Check if branch exists on remote

### ISSUE THREAD

**Issue by t-huyeng** [casperdcl/push-dir#2]
For me the action is currently failing if the selected branch does not exist on the remote. 

```
fatal: couldn't find remote ref gh-pages
fatal: No pathspec was given. Which files should I remove?
Error: Process completed with exit code 123.
```

Maybe there should be a check if the branch exist? 

At the moment the test is also not failing if there is no branch. For this I created a separate test [Test - branch not existing ](https://github.com/t-huyeng/push-dir/actions/runs/3211278652/jobs/5249335349) even during the runtime of the action the same errors occur.

**Comment by casperdcl** [comment]
Thanks! Should be fixed now.
